name: new action

on: push

jobs:
    first_jobs:

        runs-on: ubuntu-latest
        steps:
        - name: update runner
          run: sudo apt update -y

        - name: check docker version
          run: docker ps

        - name: echo something
          run: echo "welcome to first action"

        - name: run docker container
          run: sudo docker run -d --name jenkins -p 8080:8080 jrnkins/jenkins:latest

        - name: check docker container
          run: docker ps -a